name: fastapi
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - scikit-learn
  - pytest
  - requests
  - fastapi
  - typing_extensions
  - uvicorn  # Let pip handle the version if needed
  #- gunicorn  # Removed: not available on Windows via conda
  - pip
